auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
  - from: 2024-03-03
    store: tsdb
    object_store: filesystem
    schema: v12
    index:
      prefix: index_
      period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /tmp/loki

ingester:
  chunk_idle_period: 3m  # How long a chunk can remain idle before being flushed
  chunk_retain_period: 1m  # How long to keep a chunk in memory after it was closed
  max_chunk_age: 1h  # Set the maximum age of a chunk to 1 hour
  chunk_target_size: 1572864  # Target size of a chunk in bytes (1.5MB)

compactor:
  working_directory: /tmp/loki/retention
  compaction_interval: 5m
  retention_enabled: true
  retention_delete_delay: 1h
  retention_delete_worker_count: 150
  delete_request_store: filesystem

limits_config:
  retention_period: 168h # Retention for 7 days
  max_query_lookback: 168h # 7 days
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: true
  volume_enabled: true
  split_queries_by_interval: 24h
  query_timeout: 5m

pattern_ingester:
  enabled: true

