global:
  scrape_interval:     1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: rvt-ct-http-server 
    metrics_path: /prometheus
    static_configs:
      - targets:
        - rvt-ct-http-server:8088
  - job_name: rvt-ab-http-server 
    static_configs:
      - targets:
        - rvt-ab-http-server:8088
 