global:
  scrape_interval:     1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: backend 
    metrics_path: /prometheus
    static_configs:
      - targets:
        - backend:8088
  - job_name: 'kafka_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['kafka-exporter:9308']
